### ISSUE TITLE
Update beacon node with checkpointSyncURL

### ISSUE THREAD

**Issue by mFarghaly** [kotalco/community-api#110]
Ethereum beacon node spec has been updated with [check point syncing ](https://docs.prylabs.network/docs/prysm-usage/checkpoint-sync) which speeds up initial sync from finalized checkpoint rather than from genesis block.

### TODO

- [x] update beacon DTO(s) with `checkpointSyncURL:string`
- [x] creating beacon node should accept optional `checkpointSyncURL` parameter
- [x] updating beacon node should accept optional `checkpointSyncURL` parameter
